---
- hosts: fedora
  tasks:
#    - name: Cinnamon Desktop package group present
#      dnf:
#        name: '@Cinnamon Desktop'
#        state: present
    - name: cleanup NetworkManager
      package: state=absent name={{ item }}
      with_items:
        - NetworkManager-adsl
        - NetworkManager-bluetooth
        - NetworkManager-wwan
    - name: cleanup firmwares
      package: state=absent name={{ item }}
      with_items:
        - atmel-firmware
        - ipw2100-firmware
        - ipw2200-firmware
        - iwl100-firmware
        - iwl105-firmware
        - iwl135-firmware
        - iwl1000-firmware
        - iwl2000-firmware
        - iwl2030-firmware
        - iwl3160-firmware
        - iwl3945-firmware
        - iwl4965-firmware
        - iwl5000-firmware
        - iwl5150-firmware
        - iwl6000-firmware
        - iwl6000g2a-firmware
        - iwl6000g2b-firmware
        - iwl6050-firmware
        - iwl7260-firmware
        - libertas-usb8388-firmware
        - zd1211-firmware
    - name: negativo17.org nvidia repo
      get_url:
        url: https://negativo17.org/repos/fedora-nvidia.repo
        dest: /etc/yum.repos.d/fedora-nvidia.repo
    - name: install nvidia driver
      package: state=present name={{ item }}
      with_items:
        - kernel-devel
        - nvidia-driver
        - nvidia-driver-libs.i686
        - nvidia-settings
    - name: rpm-fusion present
      package: state=present name={{ item }}
      with_items:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm
    - name: steam present
      package: state=present name=steam
    - name: bluetooth items not present
      package: state=absent name=blueberry
    - name: office packages present
      package: state=present name={{ item }}
      with_items:
        - libreoffice-writer
        - libreoffice-calc
...
